import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import { SvgIconRegistryService } from 'angular-svg-icon';
import { createInjectionToken } from 'ngxtension/create-injection-token';

export const flags: string[] = [
  'AD',
  'AE',
  'AF',
  'AG',
  'AI',
  'AL',
  'AM',
  'AO',
  'AQ',
  'AR',
  'AS',
  'AT',
  'AU',
  'AW',
  'AX',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BL',
  'BM',
  'BN',
  'BO',
  'BQ-BO',
  'BQ-SA',
  'BQ-SE',
  'BR',
  'BS',
  'BT',
  'BV',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CC',
  'CD',
  'CF',
  'CG',
  'CH',
  'CI',
  'CK',
  'CL',
  'CM',
  'CN',
  'CO',
  'CR',
  'CU',
  'CV',
  'CW',
  'CX',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'EH',
  'ER',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FK',
  'FM',
  'FO',
  'FR',
  'GA',
  'GB-ENG',
  'GB-NIR',
  'GB-SCT',
  'GB-UKM',
  'GB-WLS',
  'GD',
  'GE',
  'GF',
  'GG',
  'GH',
  'GI',
  'GL',
  'GM',
  'GN',
  'GP',
  'GQ',
  'GR',
  'GS',
  'GT',
  'GU',
  'GW',
  'GY',
  'HK',
  'HM',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IM',
  'IN',
  'IO',
  'IQ',
  'IR',
  'IS',
  'IT',
  'JE',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KP',
  'KR',
  'KW',
  'KY',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MF',
  'MG',
  'MH',
  'MK',
  'ML',
  'MM',
  'MN',
  'MO',
  'MP',
  'MQ',
  'MR',
  'MS',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NC',
  'NE',
  'NF',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NU',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PF',
  'PG',
  'PH',
  'PK',
  'PL',
  'PM',
  'PN',
  'PR',
  'PS',
  'PT',
  'PW',
  'PY',
  'QA',
  'RE',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SB',
  'SC',
  'SD',
  'SE',
  'SG',
  'SH',
  'SI',
  'SJ',
  'SK',
  'SL',
  'SM',
  'SN',
  'SO',
  'SR',
  'SS',
  'ST',
  'SV',
  'SX',
  'SY',
  'SZ',
  'TC',
  'TD',
  'TF',
  'TG',
  'TH',
  'TJ',
  'TK',
  'TL',
  'TM',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'UM',
  'US',
  'UY',
  'UZ',
  'VA',
  'VC',
  'VE',
  'VG',
  'VI',
  'VN',
  'VU',
  'WF',
  'WS',
  'YE',
  'YT',
  'ZA',
  'ZM',
  'ZW',
];
export const svgIconSets = [
  { namespace: 'material_twotone', url: 'assets/icons/material-twotone.svg' },
  { namespace: 'mat_outline', url: 'assets/icons/material-outline.svg' },
  { namespace: 'mat_solid', url: 'assets/icons/material-solid.svg' },
  { namespace: 'iconsmind', url: 'assets/icons/iconsmind.svg' },
  { namespace: 'feather', url: 'assets/icons/feather.svg' },
  {
    namespace: 'heroicons_outline',
    url: 'assets/icons/heroicons-outline.svg',
  },
  { namespace: 'heroicons_solid', url: 'assets/icons/heroicons-solid.svg' },
];

export const categorizedSvgIcons = {
  anchors: [
    { name: 'cover', url: 'assets/images/anchor/cover.svg' },
    { name: 'info', url: 'assets/images/anchor/info.svg' },
    { name: 'pedigree', url: 'assets/images/anchor/pedigree.svg' },
    { name: 'show-results', url: 'assets/images/anchor/show-results.svg' },
    { name: 'health', url: 'assets/images/anchor/health.svg' },
    {
      name: 'children-siblings',
      url: 'assets/images/anchor/children-siblings.svg',
    },
    { name: 'moments', url: 'assets/images/anchor/moments.svg' },
  ],
  social: [
    { name: 'ingrus', url: 'assets/images/social/ingrus.svg' },
    {
      name: 'pedigree-online',
      url: 'assets/images/social/pedigree-online.svg',
    },
    { name: 'facebook', url: 'assets/images/social/facebook.svg' },
    { name: 'heart', url: 'assets/images/social/heart.svg' },
    { name: 'heart_solid', url: 'assets/images/social/heart_solid.svg' },
    { name: 'instagram', url: 'assets/images/social/instagram.svg' },
  ],
  petTypes: [
    { name: 'dog', url: 'assets/images/pet-type/dog.svg' },
    { name: 'cat', url: 'assets/images/pet-type/cat.svg' },
    { name: 'horse', url: 'assets/images/pet-type/horse.svg' },
  ],
  petInfo: [
    { name: 'breeder', url: 'assets/images/pet-info/breeder.svg' },
    { name: 'kennel', url: 'assets/images/pet-info/kennel.svg' },
    { name: 'owner', url: 'assets/images/pet-info/owner.svg' },
    { name: 'kennel-owner', url: 'assets/images/pet-info/kennel-owner.svg' },
    { name: 'place', url: 'assets/images/pet-info/place.svg' },
    { name: 'sex', url: 'assets/images/pet-info/sex.svg' },
    { name: 'calendar', url: 'assets/images/pet-info/calendar.svg' },
    { name: 'status', url: 'assets/images/pet-info/status.svg' },
    { name: 'coat-type', url: 'assets/images/pet-info/coat-type.svg' },
    { name: 'coat-color', url: 'assets/images/pet-info/coat-color.svg' },
    { name: 'weight', url: 'assets/images/pet-info/weight.svg' },
    { name: 'id-marking', url: 'assets/images/pet-info/id-marking.svg' },
    { name: 'city', url: 'assets/images/pet-info/city.svg' },
  ],
  background: [
    {
      name: 'cover-figure',
      url: 'assets/images/background-images/cover-figure.svg',
    },
    {
      name: 'male-figure',
      url: 'assets/images/background-images/male-figure.svg',
    },
    {
      name: 'female-figure',
      url: 'assets/images/background-images/female-figure.svg',
    },
    {
      name: 'landing-figure',
      url: 'assets/images/background-images/landing-figure.svg',
    },
    { name: 'shape-1', url: 'assets/images/background-images/shape-1.svg' },
    { name: 'shape-2', url: 'assets/images/background-images/shape-2.svg' },
    {
      name: 'footer-figure',
      url: 'assets/images/background-images/footer-figure.svg',
    },
    {
      name: 'header-figure',
      url: 'assets/images/background-images/header-figure.svg',
    },
    {
      name: 'accent-figure',
      url: 'assets/images/background-images/accent-figure.svg',
    },
  ],
  features: [
    {
      name: 'mobile_friendly',
      url: 'assets/images/features/mobile_friendly.svg',
    },
    { name: 'settings', url: 'assets/images/features/settings.svg' },
    { name: 'task_alt', url: 'assets/images/features/settings.svg' },
    { name: 'translate', url: 'assets/images/features/translate.svg' },
    { name: 'workspaces', url: 'assets/images/features/workspaces.svg' },
    { name: 'auto_stories', url: 'assets/images/features/auto_stories.svg' },
    { name: 'cached', url: 'assets/images/features/cached.svg' },
    { name: 'merge_type', url: 'assets/images/features/merge_type.svg' },
    { name: 'post_add', url: 'assets/images/features/post_add.svg' },
    { name: 'emoji_events', url: 'assets/images/features/emoji_events.svg' },
    { name: 'star_half', url: 'assets/images/features/star_half.svg' },
    { name: 'dynamic_feed', url: 'assets/images/features/dynamic_feed.svg' },
    {
      name: 'travel_explore',
      url: 'assets/images/features/travel_explore.svg',
    },
    { name: 'link', url: 'assets/images/features/link.svg' },
    { name: 'house', url: 'assets/images/features/house.svg' },
    {
      name: 'notifications',
      url: 'assets/images/features/notifications.svg',
    },
    {
      name: 'notifications_active',
      url: 'assets/images/features/notifications_active.svg',
    },
    {
      name: 'view_timeline',
      url: 'assets/images/features/view_timeline.svg',
    },
    { name: 'timeline', url: 'assets/images/features/timeline.svg' },
    {
      name: 'folder_special',
      url: 'assets/images/features/folder_special.svg',
    },
    {
      name: 'connect_without_contact',
      url: 'assets/images/features/connect_without_contact.svg',
    },
    { name: 'how_to_vote', url: 'assets/images/features/how_to_vote.svg' },
    { name: 'bug_report', url: 'assets/images/features/bug_report.svg' },
    {
      name: 'manage_search',
      url: 'assets/images/features/manage_search.svg',
    },
    { name: 'storefront', url: 'assets/images/features/storefront.svg' },
    {
      name: 'present_to_all',
      url: 'assets/images/features/present_to_all.svg',
    },
    { name: 'upload_file', url: 'assets/images/features/upload_file.svg' },
    { name: 'verified', url: 'assets/images/features/verified.svg' },
    { name: 'troubleshoot', url: 'assets/images/features/troubleshoot.svg' },
    {
      name: 'health_and_safety',
      url: 'assets/images/features/health_and_safety.svg',
    },
    {
      name: 'admin_panel_settings',
      url: 'assets/images/features/admin_panel_settings.svg',
    },
    {
      name: 'dashboard_customize',
      url: 'assets/images/features/dashboard_customize.svg',
    },
    { name: 'view_list', url: 'assets/images/features/view_list.svg' },
  ],
  common: [
    { name: 'paw', url: 'assets/images/common/paw.svg' },
    { name: 'local-offer', url: 'assets/images/common/local-offer.svg' },
    { name: 'cup', url: 'assets/images/common/cup.svg' },
    { name: 'verified', url: 'assets/images/common/verified.svg' },
    { name: 'male', url: 'assets/images/common/male.svg' },
    { name: 'female', url: 'assets/images/common/female.svg' },
    { name: 'results', url: 'assets/images/common/results.svg' },
    { name: 'phone', url: 'assets/images/common/phone.svg' },
    { name: 'mail', url: 'assets/images/common/mail.svg' },
    {
      name: 'multiple-check',
      url: 'assets/images/common/multiple-check.svg',
    },
    { name: 'question_mark', url: 'assets/images/common/question_mark.svg' },
    { name: 'contact', url: 'assets/images/common/contact.svg' },
  ],
  petServices: [
    { name: 'rent', url: 'assets/images/pet-services/rent.svg' },
    { name: 'sale', url: 'assets/images/pet-services/sale.svg' },
    {
      name: 'frozen-sperm',
      url: 'assets/images/pet-services/frozen-sperm.svg',
    },
    { name: 'mating', url: '/assets/images/pet-services/mating.svg' },
    {
      name: 'children-for-sale',
      url: 'assets/images/pet-services/children-for-sale.svg',
    },
    {
      name: 'pre-reservation',
      url: 'assets/images/pet-services/pre-reservation.svg',
    },
  ],
  menu: [
    { name: 'marketplace', url: 'assets/images/menu/marketplace.svg' },
    { name: 'welcome', url: 'assets/images/menu/welcome.svg' },
    { name: 'breed', url: 'assets/images/menu/breed.svg' },
    { name: 'post', url: 'assets/images/menu/post.svg' },
    { name: 'gift-in', url: 'assets/images/menu/gift-in.svg' },
    { name: 'litter', url: 'assets/images/menu/litter.svg' },
  ],
  patronPlaces: [
    { name: 'place-1', url: 'assets/images/patron-places/place-1.svg' },
    { name: 'place-2', url: 'assets/images/patron-places/place-2.svg' },
    { name: 'place-3', url: 'assets/images/patron-places/place-3.svg' },
    { name: 'place-4', url: 'assets/images/patron-places/place-4.svg' },
    { name: 'place-5', url: 'assets/images/patron-places/place-5.svg' },
    { name: 'place-6', url: 'assets/images/patron-places/place-6.svg' },
    { name: 'place-7', url: 'assets/images/patron-places/place-7.svg' },
    { name: 'place-8', url: 'assets/images/patron-places/place-8.svg' },
    { name: 'place-9', url: 'assets/images/patron-places/place-9.svg' },
    { name: 'place-10', url: 'assets/images/patron-places/place-10.svg' },
    { name: 'place-11', url: 'assets/images/patron-places/place-11.svg' },
    { name: 'place-12', url: 'assets/images/patron-places/place-12.svg' },
    { name: 'place-13', url: 'assets/images/patron-places/place-13.svg' },
    { name: 'place-14', url: 'assets/images/patron-places/place-14.svg' },
    { name: 'place-15', url: 'assets/images/patron-places/place-15.svg' },
    { name: 'place-16', url: 'assets/images/patron-places/place-16.svg' },
    { name: 'place-17', url: 'assets/images/patron-places/place-17.svg' },
    { name: 'place-18', url: 'assets/images/patron-places/place-18.svg' },
    { name: 'place-19', url: 'assets/images/patron-places/place-19.svg' },
    { name: 'place-20', url: 'assets/images/patron-places/place-20.svg' },
  ],
  breeds: [{ name: 'chihuahua', url: 'assets/images/breeds/chihuahua.svg' }],
  timeline: [
    { name: 'birthday', url: 'assets/images/timeline/birthday.svg' },
    {
      name: 'date-of-death',
      url: 'assets/images/timeline/date-of-death.svg',
    },
  ],
};

export const [injectIconService, provideIconService, ICON_SERVICE] =
  createInjectionToken(
    (
      domSanitizer: DomSanitizer,
      matIconRegistry: MatIconRegistry,
      registry: SvgIconRegistryService
    ) => {
      svgIconSets.forEach(iconSet => {
        const sanitizedUrl = domSanitizer.bypassSecurityTrustResourceUrl(
          iconSet.url
        );
        matIconRegistry.addSvgIconSetInNamespace(
          iconSet.namespace,
          sanitizedUrl
        );
      });

      // Register country flags
      flags.forEach(flagCode => {
        const url = `../assets/images/flags/${flagCode}.svg`;

        matIconRegistry.addSvgIcon(flagCode, url);
        registry.loadSvg(flagCode, url);
      });

      Object.values(categorizedSvgIcons).forEach(category => {
        category.forEach(icon => {
          const sanitizedUrl = domSanitizer.bypassSecurityTrustResourceUrl(
            icon.url
          );
          matIconRegistry.addSvgIcon(icon.name, sanitizedUrl);
          registry.loadSvg(String(sanitizedUrl), icon.name);
        });
      });
      return [
        {
          provide: DomSanitizer,
          useExisting: domSanitizer,
        },
        {
          provide: MatIconRegistry,
          useExisting: matIconRegistry,
        },
        {
          provide: SvgIconRegistryService,
          useExisting: registry,
        },
      ];
    },
    {
      isRoot: true,
      // extraProviders: [
      //   {
      //     provide: DomSanitizer,
      //     useExisting: DomSanitizer,
      //   },
      //   {
      //     provide: MatIconRegistry,
      //     useExisting: MatIconRegistry,
      //   },
      //   {
      //     provide: SvgIconRegistryService,
      //     useExisting: SvgIconRegistryService,
      //   },
      // ],
      deps: [DomSanitizer, MatIconRegistry, SvgIconRegistryService],
    }
  );
// provideIconServiceWithDeps
// @NgModule()
// export class IconsModule {

//   constructor(
//     private domSanitizer: DomSanitizer,
//     private matIconRegistry: MatIconRegistry,
//     private registry: SvgIconRegistryService
//   ) {
//     this.registerSvgIconSets();
//     this.registerCategorizedSvgIcons();
//   }

// }
