import { InjectionToken } from '@angular/core';
import { MOMENT_SPACE_TOKEN, POST_SPACE_TOKEN } from '@bh/post';
import {
  SPACE_URL_BREED,
  SPACE_URL_COLLECTION,
  SPACE_URL_CONTACT,
  SPACE_URL_COVER,
  SPACE_URL_EVENT,
  SPACE_URL_KENNEL,
  SPACE_URL_LITTER,
  SPACE_URL_LOOKUP,
  SPACE_URL_MARKETPLACE,
  SPACE_URL_MOMENT,
  SPACE_URL_NOTE,
  SPACE_URL_PET,
  SPACE_URL_POST,
} from '@bh/space-url';
import { SpaceConfig } from '@bh/superfield';
import { CONTAC_SPACE_TOKEN } from '@bp/chromatin/contact';
import { BREED_SPACE_TOKEN } from '@breedpride/breed';
import {
  COLLECTION_SPACE_TOKEN,
  SPACE_CONFIG_MY_COLLECTION_TOKEN,
} from '@breedpride/collection';
import { SPACE_CONFIG_COVER_TOKEN } from '@breedpride/cover';
import { EVENT_SPACE_TOKEN } from '@breedpride/event';
import { KENNEL_SPACE_TOKEN } from '@breedpride/kennel';
import {
  LITTER_SPACE_TOKEN,
  SPACE_CONFIG_MY_LITTER_TOKEN,
} from '@breedpride/litter';
import { LOOKUP_SPACE_TOKEN } from '@breedpride/lookup';
import { SPACE_CONFIG_NOTE_TOKEN } from '@breedpride/note';
import {
  MARKETPLACE_SPACE_TOKEN,
  PET_SPACE_TOKEN,
  SPACE_CONFIG_MY_MARKETPLACE_TOKEN,
  SPACE_CONFIG_MY_PET_TOKEN,
} from '@breedpride/pet';

export const PATH_SPACE_TOKENS: Record<string, InjectionToken<SpaceConfig>> = {
  [SPACE_URL_PET]: PET_SPACE_TOKEN,
  [SPACE_URL_BREED]: BREED_SPACE_TOKEN,
  [SPACE_URL_KENNEL]: KENNEL_SPACE_TOKEN,
  [SPACE_URL_CONTACT]: CONTAC_SPACE_TOKEN,
  [SPACE_URL_EVENT]: EVENT_SPACE_TOKEN,
  [SPACE_URL_LOOKUP]: LOOKUP_SPACE_TOKEN,
  [SPACE_URL_POST]: POST_SPACE_TOKEN,
  [SPACE_URL_MOMENT]: MOMENT_SPACE_TOKEN,
  [SPACE_URL_COLLECTION]: COLLECTION_SPACE_TOKEN,
  [SPACE_URL_LITTER]: LITTER_SPACE_TOKEN,
  [SPACE_URL_MARKETPLACE]: MARKETPLACE_SPACE_TOKEN,
};

export const MY_PATH_SPACE_CONFIGS_TOKEN: Record<
  string,
  InjectionToken<SpaceConfig>
> = {
  [SPACE_URL_PET]: SPACE_CONFIG_MY_PET_TOKEN,
  [SPACE_URL_COLLECTION]: SPACE_CONFIG_MY_COLLECTION_TOKEN,
  [SPACE_URL_LITTER]: SPACE_CONFIG_MY_LITTER_TOKEN,
  [SPACE_URL_MARKETPLACE]: SPACE_CONFIG_MY_MARKETPLACE_TOKEN,
  [SPACE_URL_COVER]: SPACE_CONFIG_COVER_TOKEN,
  [SPACE_URL_NOTE]: SPACE_CONFIG_NOTE_TOKEN,
};

