// @index(['./**/*.{ts,tsx}', './*/index.{ts,tsx}'], f => `export * from '${f.path.replace(/\/index$/, '')}'`)
export * from './lib/avatar-card/avatar-card.component'
export * from './lib/breed-achievements/breed-achievements.component'
export * from './lib/breed-element-top-patrons/breed-element-top-patrons.component'
export * from './lib/breed-list-card/breed-list-card.component'
export * from './lib/breed-name/breed-name.component'
export * from './lib/breed-progress-ligh/breed-progress-ligh.component'
export * from './pages/breed-page/breed-space'
export * from './pages/breed-page/breed.routing'
export * from './pages/breed-page/components/breed-moments/breed-moments.component'
export * from './pages/breed-page/components/breed-patrons/breed-patrons.component'
export * from './pages/breed-page/components/breed-support-levels/breed-support-levels.component'
export * from './pages/breed-page/components/breed-top-kennels/breed-top-kennels.component'
export * from './pages/breed-page/components/breed-top-pets/breed-top-pets.component'
// @endindex
